name: 'build and deploy'
on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install npm
        run: cd frontend && npm ci
      - name: Build
        run: cd frontend && npm run build
      - run: cd frontend && ls
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: frontend/build

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build
      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: '.'
          bucket: ${{ secrets.S3_BUCKET_WEB }}
          bucket-region: us-east-1
      

